pipeline{
    agent any
        stages{
            stage('Checkout SCM'){
               steps{
                   git credentialsId: 'c4bca1fe-d6fe-4fd5-8edd-bd49e9c49701', url: 'https://github.com/RaviT17/Devops_Demo.git'
               }
               }
        
            stage('Run Ansible Playbook'){
                steps{
                   ansiblePlaybook become: true, becomeUser: null, credentialsId: '6b660bbb-ae80-4491-ac10-37f8710fc0ac', disableHostKeyChecking: true, installation: 'Ansible', inventory: 'AnsibleRep/hosts', playbook: 'AnsibleRep/playbook.yml'
                }
            }
        }
        
}
